/* *****************************************************************************
 *  Name:              Ada Lovelace
 *  Coursera User ID:  123456
 *  Last modified:     October 16, 1842
 **************************************************************************** */

public class PercolationTests {
    public static void main(String[] args) {
        // Percolation p = new Percolation(enteredN);
        // p.open(3, 3);
        // p.printGrid();
        // System.out.println();
        // p.open(3, 4);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(2, 1);
        // p.printGrid();
        // System.out.println();
        // p.open(1, 3);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 4);
        // p.printGrid();
        // System.out.println();
        // p.open(0, 2);
        // p.printGrid();
        // System.out.println();
        // p.open(0, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(3, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(3, 4);
        // p.printGrid();
        // System.out.println();
        // p.open(3, 1);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 1);
        // p.printGrid();
        // System.out.println(p.percolates());


        // Percolation p = new Percolation(enteredN);
        // p.open(4, 4);
        // p.printGrid();
        // System.out.println();
        // p.open(0, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 2);
        // p.printGrid();
        // System.out.println();
        // p.open(1, 3);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 3);
        // p.printGrid();
        // System.out.println();
        // p.open(3, 1);
        // p.printGrid();
        // System.out.println();
        // p.open(1, 2);
        // p.printGrid();
        // System.out.println();
        // p.open(2, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(2, 3);
        // p.printGrid();
        // System.out.println();
        // p.open(3, 2);
        // p.printGrid();
        // System.out.println();
        // p.open(0, 4);
        // p.printGrid();
        // System.out.println();
        // p.open(0, 2);
        // p.printGrid();
        // System.out.println();
        // p.open(2, 1);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 4);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 1);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(2, 4);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(2, 2);
        // p.printGrid();
        // System.out.println(p.percolates());


        // Percolation p = new Percolation(enteredN);
        // p.open(3, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 1);
        // p.printGrid();
        // System.out.println();
        // p.open(2, 2);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 2);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 4);
        // p.printGrid();
        // System.out.println();
        // p.open(3, 4);
        // p.printGrid();
        // System.out.println();
        // p.open(3, 1);
        // p.printGrid();
        // System.out.println();
        // p.open(1, 3);
        // p.printGrid();
        // System.out.println();
        // p.open(0, 2);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 4);
        // p.printGrid();
        // System.out.println();
        // p.open(3, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(0, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(0, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 3);
        // p.printGrid();
        // System.out.println(p.percolates());

        // Percolation p = new Percolation(enteredN);
        // p.open(4, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(3, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(2, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(0, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(1, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(3, 1);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 1);
        // p.printGrid();
        // System.out.println(p.percolates());

        // Percolation p = new Percolation(enteredN);
        // p.open(3, 4);
        // p.printGrid();
        // System.out.println();
        // p.open(2, 4);
        // p.printGrid();
        // System.out.println();
        // p.open(1, 4);
        // p.printGrid();
        // System.out.println();
        // p.open(2, 3);
        // p.printGrid();
        // System.out.println();
        // p.open(2, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(0, 1);
        // p.printGrid();
        // System.out.println();
        // p.open(2, 2);
        // p.printGrid();
        // System.out.println();
        // p.open(1, 3);
        // p.printGrid();
        // System.out.println();
        // p.open(0, 0);
        // p.printGrid();
        // System.out.println();
        // p.open(1, 1);
        // p.printGrid();
        // System.out.println();
        // p.open(3, 2);
        // p.printGrid();
        // System.out.println();
        // p.open(4, 2);
        // p.printGrid();
        // System.out.println(p.percolates());
        // System.out.println();
        // p.open(2, 1);
        // p.printGrid();
        // System.out.println(p.percolates());
    }
}
